name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          user: mikeagubi
          template: classic
          config_timezone: Europe/Stockholm

          # THEME (som bilden)
          config_display: large
          config_padding: 16
          config_octicon: yes
          config_twemoji: yes

          # CONTRIBUTIONS / STREAK
          plugin_streak: yes
          plugin_streak_days: yes

          # LANGUAGES (DONUTS)
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size,percentage
          plugin_languages_threshold: 2
          plugin_languages_charts: yes
          plugin_languages_charts_type: donut

          # STATS + BIG CAT
          plugin_notable: yes
          plugin_notable_from: all

          # COMMITS PER HOUR
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # ACTIVITY GRAPH (AREA)
          plugin_activity: yes
          plugin_activity_limit: 12
          plugin_activity_days: 365
          plugin_activity_filter: all

          # OUTPUT
          filename: metrics.svg
